name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python:
    runs-on: self-hosted  # Local runner

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Create and activate a temporary Conda environment
      - name: Create and Activate Conda Environment
        shell: bash -l {0}
        run: |
          conda create -n temp-ci-env python=3.10 -y
          conda activate temp-ci-env
          pip install -r requirements.txt

      # Run Unit Tests
      - name: Run Unit Tests
        shell: bash -l {0}
        run: |
          conda activate temp-ci-env
          python -m unittest discover tests

      # Clean up the temporary Conda environment
      - name: Remove Temporary Conda Environment
        if: always()
        shell: bash -l {0}
        run: |
          conda remove -n temp-ci-env --all -y
