name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python:
    strategy:
      matrix:
        os: [self-hosted, ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # For GitHub-hosted runners: use system Python and pip instead of conda
      - name: Setup Python and Install Dependencies (GitHub-Hosted)
        if: ${{ matrix.os != 'self-hosted' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests (GitHub-Hosted)
        if: ${{ matrix.os != 'self-hosted' }}
        run: |
          python -m unittest discover tests

      # Existing self-hosted configuration
      - name: Create and Activate Conda Environment (Self-hosted)
        if: ${{ matrix.os == 'self-hosted' }}
        shell: bash -l {0}
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh  # Dynamically source Conda initialization
          conda create -n temp-ci-env python=3.10 -y
          conda activate temp-ci-env
          pip install -r requirements.txt

      - name: Run Unit Tests (Self-hosted)
        if: ${{ matrix.os == 'self-hosted' }}
        shell: bash -l {0}
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh  # Dynamically source Conda initialization
          conda activate temp-ci-env
          python -m unittest discover tests

      - name: Remove Temporary Conda Environment (Self-hosted)
        if: ${{ matrix.os == 'self-hosted' }}
        shell: bash -l {0}
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh
          conda remove -n temp-ci-env --all -y