name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python:
    strategy:
      matrix:
        os: [self-hosted, ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Create and activate a temporary Conda environment
      - name: Create and Activate Conda Environment
        shell: bash -l {0}
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh  # Dynamically source Conda initialization
          conda create -n temp-ci-env python=3.10 -y
          conda activate temp-ci-env
          pip install -r requirements.txt

      # Run Unit Tests
      - name: Run Unit Tests
        shell: bash -l {0}
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh  # Dynamically source Conda initialization
          conda activate temp-ci-env
          python -m unittest discover tests

      # Clean up the temporary Conda environment
      - name: Remove Temporary Conda Environment
        if: always()
        shell: bash -l {0}
        run: |
          source $(conda info --base)/etc/profile.d/conda.sh  # Dynamically source Conda initialization
          conda remove -n temp-ci-env --all -y